- 1.1.13
- _NAME: G Pro Wireless Gaming Mouse
  _modelId: 4079C0880000
  _sensitive: {dpi: true}
  _serial: 3CA275D7
  _unitId: 3CA275D7
  _wpid: '4079'
  dpi: 400
  onboard_profiles: 1
  report_rate: 1
- _NAME: MX Master 3 Wireless Mouse
  _dpi-sliding: 8
  _modelId: B02340820000
  _sensitive: {dpi: false, dpi-sliding: false, hires-smooth-resolution: false, mouse-gestures: false, smart-shift: false, thumb-scroll-invert: false}
  _serial: 9260BEFA
  _unitId: 9260BEFA
  _wpid: '4082'
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 1, 196: 0}
  dpi: 600
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 2
  smart-shift: 30
  thumb-scroll-invert: true
  thumb-scroll-mode: false
- _NAME: MX Master 3 Wireless Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight,
    backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control,
    rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys,
    m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 0
  _modelId: B02340820000
  _sensitive: {divert-keys: true, dpi: true, hires-smooth-resolution: true, reprogrammable-keys: false, scroll-ratchet: false, smart-shift: true, thumb-scroll-invert: true}
  _serial: 141C51BD
  _unitId: 141C51BD
  _wpid: '4082'
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 0, 196: 0}
  dpi: 600
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 2
  smart-shift: 40
  thumb-scroll-invert: true
  thumb-scroll-mode: false
- _NAME: Wireless Mouse MX Master 2S
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 7930D8AF
  _wpid: '4069'
- _NAME: PRO X Wireless
  _modelId: 4093C0940000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: E1675677
  _unitId: E1675677
  _wpid: '4093'
  dpi: 800
  onboard_profiles: 1
  report_rate: 1
- _NAME: MX Master 3 Wireless Mouse
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _wpid: '4082'
- _NAME: Wireless Mouse B330/M330/M331
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, report_rate_extended, dpi, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in,
    backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert,
    gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: '405700000000'
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: BDECAD34
  _unitId: BDECAD34
  _wpid: '4057'
  divert-keys: {80: 0, 81: 0, 82: 0}
  lowres-scroll-mode: false
  pointer_speed: 256
  reprogrammable-keys: {80: 80, 81: 81, 82: 82}
