sourceDir = "/home/fezjo/src/configuration/linux/chezmoi/"

# [diff]
# #command = "delta"
# pager = "delta"

# [diff]
# command = "code"
# args = ["--wait", "--diff"]

[diff]
command = "difft"
args = [
  "--color",
  "always",
  "--skip-unchanged",
]
pager = "bat"
