[opener]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
  { run = 'vlc "$@"', orphan = true, for = "unix" },
	{ run = 'mpv --force-window %*', orphan = true, for = "windows" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
